/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class radium_DLib__ */

#ifndef _Included_radium_DLib__
#define _Included_radium_DLib__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     radium_DLib__
 * Method:    landmarks0
 * Signature: (Ljava/lang/String;II[B)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_radium_DLib_00024_landmarks0
  (JNIEnv *, jobject, jstring, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
