/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class radium_Adder */

#ifndef _Included_radium_Adder
#define _Included_radium_Adder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     radium_Adder
 * Method:    toPoint
 * Signature: (II)Lradium/Point;
 */
JNIEXPORT jobject JNICALL Java_radium_Adder_toPoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     radium_Adder
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_radium_Adder_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     radium_Adder
 * Method:    toRectangle
 * Signature: ()Lradium/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_radium_Adder_toRectangle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
